// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'title': string;
  'ulWrap': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
